In [1]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
import sklearn.datasets as datasets

In [2]:
x_train=np.array([[2,1],[1,-1]])
y_train=np.array([[3],[1]])

In [3]:
lrg=LinearRegression()
lrg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [4]:
coef_=lrg.coef_
np.dot(coef_,x_train)#逻辑回归

array([[ 1.6, -0.4]])

In [5]:
coef_

array([[0.4, 0.8]])

In [6]:
x_train=np.array([[2,1,2,1],[2,3,2,3]])
y_train=np.array([[1.2],[3]])

In [7]:
lrg=LinearRegression()
lrg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [8]:
lrg.predict([[3,4,4,3]])#逻辑回归

array([[3.45]])

In [9]:
lrg.coef_

array([[1.11022302e-16, 4.50000000e-01, 0.00000000e+00, 4.50000000e-01]])

In [14]:
#岭回归
from sklearn.linear_model import Ridge

In [29]:
x_train=np.array([[2,1],[1,-1]])
y_train=np.array([3,1])

In [30]:
ridge=Ridge(alpha=2)

In [31]:
ridge.fit(x_train,y_train)
ridge.predict([[1,2]])

array([2.77777778])