In [2]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
import sklearn.datasets as datasets

In [3]:
x=[[0,0,0],[1,1,1]]
y=[0,1]

In [5]:
lng=LinearRegression()
lng.fit(x,y)
lng.predict(np.array([[2,2,2]]))

array([2.])

In [6]:
ridge=Ridge(alpha=1)#岭回归，alph放弃特征的数量
ridge.fit(x,y)
ridge.predict(np.array([[2,2,2]]))

array([1.4])

In [7]:
ridge.coef_

array([0.2, 0.2, 0.2])

In [8]:
ridge.intercept_

0.19999999999999996